### ISSUE TITLE
Remove AmlCompute.supported_vmsizes from the generated notebook, it creates a lot of un-needed noise:

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/automl-codegen-preview#2]
@wchill

Remove this code from the generated notebook, it creates a lot of un-needed noise:

AmlCompute.supported_vmsizes(workspace = ws)

![image](https://user-images.githubusercontent.com/1712635/129418052-60231689-56bb-42bb-9478-133765f51d06.png)

**Comment by wchill** [comment]
This will be removed in the next private preview version.

**Comment by wchill** [comment]
This is fixed now.
